# Setup
title:               Global Missions Week
tagline:             Southeastern Baptist Theological Seminary
description:         '<img src="/public/cgcs-logo-blue.png" class="center">'
url:                 https://missionsweek.tk
baseurl:             ''
paginate:            0
permalink:           pretty
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Center for Great Commission Studies
  url:               https://twitter.com/thecgcs
  email:             kcook@sebts.edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom vars
version:             0.1.0
google_analytics_id: 251844397
