# Setup
title:               Sending Pathways
tagline:             From your church to the ends of the earth.
description:         '<img src="/public/pathways2.png" class="center">'
url:                 https://keelancook.com/pathways-test1
baseurl:             ''
paginate:            5
permalink:           pretty
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Keelan Cook
  url:               https://twitter.com/keelancook
  email:             kcook@sebts.edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom vars
version:             0.1.0
google_analytics_id: 251844397
